controller_manager:
  ros__parameters:
    update_rate: 10     # Data being send 10 times a second.
    use_sim_time: false # Keep this value false when workign with real hardware.

    mec_cont:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    
## Directly below the controller_manager section

mec_cont:
  ros__parameters:
    
    reference_timeout: 0.0 #1.0      # Amount of time for which to apply the received command. If new command is receview, existinf will be overriden.
    # set 0.0 to stop after key is released and 1.0 to continuously move untill next key is pressed. Setting mid value like 0.5 or negative value like -1.0 will lead to continuous movement like with 1.0.
    
    #publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    #reference_timeout: 0.1   
    
    #left_wheel_names: ['left_wheel_joint']  
    #right_wheel_names: ['right_wheel_joint']
    
    #WORKING(INITIAL): command_joint_names: ["dummy_left_joint", "left_wheel_joint", "right_wheel_joint", "dummy_right_joint"]
    #WORKING(BEST_FOR_NORMAL_WHEEL): command_joint_names: ["dummy_left_joint", "dummy_right_joint", "left_wheel_joint", "right_wheel_joint"]
    
    
    # Not Working:
    #command_joint_names: ["dummy_right_joint", "dummy_left_joint", "right_wheel_joint", "left_wheel_joint"]
    #command_joint_names: ["dummy_right_joint", "right_wheel_joint", "dummy_left_joint", "left_wheel_joint"]
    #command_joint_names: ["dummy_left_joint", "dummy_right_joint", "right_wheel_joint", "left_wheel_joint"]
    #command_joint_names: ["left_wheel_joint", "right_wheel_joint", "dummy_left_joint", "dummy_right_joint"]
            
    
    command_joint_names: ["front_left_joint", "rear_left_joint", "rear_right_joint", "front_right_joint"]                
    
    #command_joint_names: ["dummy_left_joint", "left_wheel_joint", "right_wheel_joint", "dummy_right_joint"]        # BEST
    #command_joint_names: ["dummy_left_joint", "dummy_right_joint", "left_wheel_joint", "right_wheel_joint"]
    #command_joint_names: ["left_wheel_joint", "dummy_right_joint", "right_wheel_joint", "dummy_left_joint", ]        
            
    interface_name: velocity
    
    #wheel_separation: 0.35
    #wheel_radius: 0.05
    
    kinematics:
        wheels_radius: 0.056 #0.4
        sum_of_robot_center_projection_on_X_Y_axis: 0.6       # Default 1.0        
        
    base_frame_id: "base_link"
    odom_frame_id: "odom" 
    
    
    enable_odom_tf: true 
         
    #working use_stamped_vel: false
    use_stamped_vel: true

               
    
# joint_broad:
#   ros__parameters:

