controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    mec_cont:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
        
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    
## Directly below the controller_manager section

mec_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    #left_wheel_names: ['left_wheel_joint']  
    #right_wheel_names: ['right_wheel_joint']
    
    #WORKING(INITIAL): command_joint_names: ["dummy_left_joint", "left_wheel_joint", "right_wheel_joint", "dummy_right_joint"]
    #WORKING(BEST_FOR_NORMAL_WHEEL): command_joint_names: ["dummy_left_joint", "dummy_right_joint", "left_wheel_joint", "right_wheel_joint"]
    
    
    # Not Working:
    #command_joint_names: ["dummy_right_joint", "dummy_left_joint", "right_wheel_joint", "left_wheel_joint"]
    #command_joint_names: ["dummy_right_joint", "right_wheel_joint", "dummy_left_joint", "left_wheel_joint"]
    #command_joint_names: ["dummy_left_joint", "dummy_right_joint", "right_wheel_joint", "left_wheel_joint"]
    #command_joint_names: ["left_wheel_joint", "right_wheel_joint", "dummy_left_joint", "dummy_right_joint"]
            
    command_joint_names: ["dummy_left_joint", "left_wheel_joint", "right_wheel_joint", "dummy_right_joint"]        # BEST
    #command_joint_names: ["dummy_left_joint", "dummy_right_joint", "left_wheel_joint", "right_wheel_joint"]
    #command_joint_names: ["left_wheel_joint", "dummy_right_joint", "right_wheel_joint", "dummy_left_joint", ]        
            
    interface_name: velocity
    
    #wheel_separation: 0.35
    #wheel_radius: 0.05
    
    kinematics:
        wheels_radius: 0.4 #0.4
        sum_of_robot_center_projection_on_X_Y_axis: 1.0       # Default 1.0
        
    #working use_stamped_vel: false
    use_stamped_vel: true
        

joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - base_link_x_y
      - base_link_y_z
      - base_link_z_1
      - l3_joint
      
    command_interfaces:
      - position

    state_interfaces:
      - position

    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)      
    
# joint_broad:
#   ros__parameters:

