<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="arm_macro">

        <xacro:include filename="inertial_macros.xacro" />
        
        
        <!-- Variables -->
        <xacro:property name="sphere_radius" value="0.1"/>
        <xacro:property name="sphere_mass" value="0.5"/>
        
        <xacro:property name="l2_length" value="0.5"/>
        <xacro:property name="l3_length" value="0.3"/>
        <xacro:property name="l4_length" value="0.15"/>
        
        <xacro:property name="racquet_thickness" value="0.02"/>
        <xacro:property name="racquet_radius" value="0.2"/>    
            
        <xacro:property name="general_mass" value="0.1"/>
        <xacro:property name="general_radius" value="0.02"/>
                    
        <!-- MATERIALS -->
        
        <!--
        <material name="Purple">
            <color rgba="1 0.2 1 1"/>
        </material>     
        -->
        
        <material name="Black">
          <color rgba="0.0 0.0 0.0 1.0"/>
        </material>

        <material name="Blue">
          <color rgba="0.0 0.0 0.8 1.0"/>
        </material>

        <material name="Green">
          <color rgba="0.0 0.8 0.0 1.0"/>
        </material>

        <material name="Grey">
          <color rgba="0.2 0.2 0.2 1.0"/>
        </material>

        <material name="Orange">
          <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
        </material>

        <material name="Brown">
          <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
        </material>

        <material name="Red">
          <color rgba="0.8 0.0 0.0 1.0"/>
        </material>

        <material name="Yellow">
          <color rgba="1.0 1.0 0.0 1.0"/>
        </material>
        
        <!--
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0"/>
        </material>
        -->
            
        <!-- ARM LINK MACRO -->
        <xacro:macro name="link_macro" params="name length radius color *origin">
            
            <link name="${name}">
                <visual>
                    <xacro:insert_block name="origin"/>
                    <geometry>
                        <cylinder length="${length}" radius="${radius}" />
                    </geometry>
                    <material name="${color}"/>
                </visual>
                    
                <collision>
                    <geometry>
                        <cylinder length="${length}" radius="${radius}" />
                    </geometry>
                </collision>
                
                <xacro:inertial_cylinder mass="${general_mass}" length="${length}" radius="${radius}" >
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                </xacro:inertial_cylinder>
                
            </link>
            
            <gazebo reference="${name}">
                <material>Gazebo/${color}</material>
                <!-- <material>Gazebo/Purple</material> -->
            </gazebo>
        
        </xacro:macro>     
        
        <!-- BASE LINK -->
        <!-- <link name="base_link"/>    -->
        
        <!--    
        <link name="base_link_x"/>
        <link name="base_link_y"/>
        <link name="base_link_z"/>
        -->
        
        <xacro:link_macro name="base_link_x" length="0.000001" radius="0.000001" color="Red">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:link_macro>    
        
        <xacro:link_macro name="base_link_y" length="0.000001" radius="0.000001" color="Red">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:link_macro>    
        
        <xacro:link_macro name="base_link_z" length="0.000001" radius="0.000001" color="Red">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:link_macro>    

        
        
        <!-- JOINTS -->
        <joint name="ground" type="fixed">
            <parent link="chassis_link"/>
            <child link="base_link_x"/>
            <origin xyz="0 0 0.12" rpy="0 0 0"/>              
        </joint>    
        
        <joint name="base_link_x_y" type="revolute">
            <parent link="base_link_x"/>
            <child link="base_link_y"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <limit upper="${pi/2}" lower="${-pi/2}" velocity="20" effort="1"/>        
            <axis xyz="1 0 0"/> 
        </joint>
        
        <joint name="base_link_y_z" type="revolute">
            <parent link="base_link_y"/>
            <child link="base_link_z"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <limit upper="${pi/2}" lower="${-pi/2}" velocity="20" effort="1"/>
            <axis xyz="0 1 0"/> 
        </joint>    
        
        <!-- LINK_1 --> 
        <joint name="base_link_z_1" type="continuous">
            <parent link="base_link_z"/>
            <child link="link_1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <axis xyz="0 0 1"/> 
        </joint>
        
        <link name="link_1">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${sphere_radius}"/>    
                </geometry>            
                <material name="Red"/>
            </visual>
            
            <collision>
                <geometry>
                    <sphere radius="${sphere_radius}"/>    
                </geometry>                                    
            </collision>
            
            <xacro:inertial_sphere mass="${sphere_mass}" radius="${sphere_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>            
            </xacro:inertial_sphere>
        </link>   
        
        <gazebo reference="link_1">
            <material>Gazebo/Red</material>
        </gazebo>        
        
        <!-- LINK_2 -->     
        <joint name="l2_joint" type="fixed">
            <parent link="link_1"/>
            <child link="link_2"/>
            <origin xyz="0 0 ${sphere_radius}" rpy="0 0 0"/>
            <!-- <axis xyz="0 0 0"/> -->
        </joint>
        
        <xacro:link_macro name="link_2" length="${l2_length}" radius="${general_radius}" color="Yellow">
            <origin xyz="0 0 ${l2_length/2}" rpy="0 0 0"/>
        </xacro:link_macro>
        
        <!-- LINK_3 -->     
        <joint name="l3_joint" type="revolute">
            <parent link="link_2"/>
            <child link="link_3"/>
            <origin xyz="0 0 ${l2_length + general_radius}" rpy="0 0 0"/>
            <limit upper="${pi/2}" lower="${-pi/2}" velocity="20" effort="1"/>
            <axis xyz="1 0 0"/>
        </joint>
        
        <xacro:link_macro name="link_3" length="${l3_length}" radius="${general_radius}" color="Green">
            <origin xyz="0 0 ${l3_length/2}" rpy="0 0 0"/>
        </xacro:link_macro>
        
        <!-- LINK_4 -->     
        <!--
        <joint name="l4_joint" type="continuous">
            <parent link="link_3"/>
            <child link="link_4"/>
            <origin xyz="0 0 ${l3_length + general_radius}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
        </joint>
        
        <xacro:link_macro name="link_4" length="${l4_length}" radius="${general_radius}" color="Orange">
            <origin xyz="0 0 ${l4_length/2}" rpy="0 0 0"/>
        </xacro:link_macro>
        -->
        
        <!-- LINK_5 (Racquet)-->     
        <joint name="racquet_joint" type="fixed">
            <parent link="link_3"/>
            <child link="racquet_link"/>
            <origin xyz="0 0 ${l3_length + racquet_radius}" rpy="${pi/2} 0 0"/>
        </joint>
        
        <xacro:link_macro name="racquet_link" length="${racquet_thickness}" radius="${racquet_radius}" color="Blue">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:link_macro>
    
    </xacro:macro>    
    
</robot>
